<a href="https://colab.research.google.com/github/m4vic/seq-to-seq-pytorch/blob/main/RNN/RNN_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**STRATEGY**

1.   load dataset (csv)
2.   eng sentence --> index
3.  index to embeddings
4.  embeddings model --> vector
5.  RNn architecture
6. Training



loading dataset

In [1]:
import pandas as pd

df = pd.read_csv('/content/100_Unique_QA_Dataset.csv')
df.head()



question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [2]:
df.head()

question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [3]:
# tokenize
def tokenize(text):
  tect = text = text.lower()
  text.replace('?','')
  text.replace("'","")
  return text.split()

In [4]:
# vocab
vocab = {'<UNK>':0}

In [5]:
def build_vocab(row):
  print(row['question'])
  tokenized_question = tokenize(row['question'])
  tokenized_answer = tokenize(row['answer'])

  mearged = tokenized_question + tokenized_answer # mearging the tokenized question and as

  for word in mearged:
    if word not in vocab: # checking the word in vocab
      vocab[word] = len(vocab) # word will be added into vocab if not , as index no.




In [6]:
df.apply(build_vocab,axis=1)

What is the capital of France?
What is the capital of Germany?
Who wrote 'To Kill a Mockingbird'?
What is the largest planet in our solar system?
What is the boiling point of water in Celsius?
Who painted the Mona Lisa?
What is the square root of 64?
What is the chemical symbol for gold?
Which year did World War II end?
What is the longest river in the world?
What is the capital of Japan?
Who developed the theory of relativity?
What is the freezing point of water in Fahrenheit?
Which planet is known as the Red Planet?
Who is the author of '1984'?
What is the currency of the United Kingdom?
What is the capital of India?
Who discovered gravity?
How many continents are there on Earth?
Which gas do plants use for photosynthesis?
What is the smallest prime number?
Who invented the telephone?
What is the capital of Australia?
Which ocean is the largest?
What is the speed of light in vacuum?
Which language is spoken in Brazil?
Who discovered penicillin?
What is the capital of Canada?
What is 

0     None
1     None
2     None
3     None
4     None
      ... 
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [7]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france?': 6,
 'paris': 7,
 'germany?': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 "'to": 12,
 'kill': 13,
 'a': 14,
 "mockingbird'?": 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system?': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius?': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa?': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64?': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold?': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end?': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'world?': 52,
 'nile': 53,
 'japan?': 54,
 'tokyo': 55,
 'developed': 56,
 'theory': 57,
 'relativity?': 58,
 'albert-einstein': 59,
 'freezing': 60,
 'fahrenheit?': 61,
 '32': 62,
 'known': 63,
 'as': 64,
 'red': 65,
 'planet?': 66,
 'mars': 67,
 'author': 68,
 "'1984'?": 6

In [8]:
len(vocab)

337

In [9]:
# convert words to numerical indies

def word_to_index(text,vocab):

  indexed_text = []

  for token in tokenize(text): # iterate each word

    if token in vocab: # if token word in vocab word appen the indexed.text with vocab token

      indexed_text.append(vocab[token])

    else: # else append index_text with Unk index un known index

      indexed_text.append(vocab['<UNK>'])

  return indexed_text

In [10]:
word_to_index('this is sanskar', vocab)  # 0 = unknown means the this and sanskar is not present in the vocab and is index is 2

[0, 2, 0]

In [11]:
import torch
from torch.utils.data import Dataset, DataLoader

In [12]:
class QADataset(Dataset):
  def __init__(self,df,vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return len(self.df)

  def __getitem__(self,idx):
   # retriving the question from dataset
    neumerical_question = word_to_index(self.df.iloc[idx]['question'],self.vocab)
    neumerical_ans = word_to_index(self.df.iloc[idx]['answer'],self.vocab)

    return torch.tensor(neumerical_question), torch.tensor(neumerical_ans)




In [13]:
dataset = QADataset(df,vocab)

In [14]:
dataset[2]

(tensor([10, 11, 12, 13, 14, 15]), tensor([16]))

In [15]:
dataloader = DataLoader(dataset,batch_size=1)

In [16]:
for question, answer in dataloader:
  print(question, answer)



tensor([[1, 2, 3, 4, 5, 6]]) tensor([[7]])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([[9]])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([[16]])
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]) tensor([[23]])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([[28]])
tensor([[10, 29,  3, 30, 31]]) tensor([[32]])
tensor([[ 1,  2,  3, 33, 34,  5, 35]]) tensor([[36]])
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([[41]])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([[49]])
tensor([[ 1,  2,  3, 50, 51, 19,  3, 52]]) tensor([[53]])
tensor([[ 1,  2,  3,  4,  5, 54]]) tensor([[55]])
tensor([[10, 56,  3, 57,  5, 58]]) tensor([[59]])
tensor([[ 1,  2,  3, 60, 25,  5, 26, 19, 61]]) tensor([[62]])
tensor([[42, 18,  2, 63, 64,  3, 65, 66]]) tensor([[67]])
tensor([[10,  2,  3, 68,  5, 69]]) tensor([[70]])
tensor([[ 1,  2,  3, 71,  5,  3, 72, 73]]) tensor([[74]])
tensor([[ 1,  2,  3,  4,  5, 75]]) tensor([[76]])
tensor([[10, 77, 78]]) tensor([[79]])
tensor([[80, 81, 82, 83, 84, 85, 86]]) tensor([[87]])
tens

# *Building RNN*

In [17]:
import torch.nn as nn

In [18]:
class SimpleRNN(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
    self.rnn = nn.RNN(50, 64, batch_first=True)
    self.fc = nn.Linear(64,vocab_size)

  def forward(self, question):
    embedded_question = self.embedding(question)
    hidden, final = self.rnn(embedded_question)
    output = self.fc(final.squeeze(0))

    return output


In [31]:
learning_rate = 0.001
epochs = 100
model = SimpleRNN(len(vocab))

In [32]:

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


In [33]:
# training loop

for epoch in range(epochs):

  total_loss = 0

  for question, answer in dataloader:

    optimizer.zero_grad()

    # forward pass
    output = model(question)

    # loss -> output shape (1,337) - (1)
    loss = criterion(output, answer[0])

    # gradients
    loss.backward()

    # update
    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch+1}, Loss: {total_loss:4f}")

Epoch: 1, Loss: 526.230700
Epoch: 2, Loss: 456.749376
Epoch: 3, Loss: 375.076053
Epoch: 4, Loss: 313.407042
Epoch: 5, Loss: 261.103238
Epoch: 6, Loss: 212.606066
Epoch: 7, Loss: 168.703836
Epoch: 8, Loss: 130.840442
Epoch: 9, Loss: 100.050346
Epoch: 10, Loss: 76.341998
Epoch: 11, Loss: 58.799973
Epoch: 12, Loss: 46.086449
Epoch: 13, Loss: 36.878896
Epoch: 14, Loss: 30.106665
Epoch: 15, Loss: 25.004119
Epoch: 16, Loss: 21.061111
Epoch: 17, Loss: 17.945361
Epoch: 18, Loss: 15.436246
Epoch: 19, Loss: 13.381661
Epoch: 20, Loss: 11.673715
Epoch: 21, Loss: 10.235937
Epoch: 22, Loss: 9.015320
Epoch: 23, Loss: 7.974927
Epoch: 24, Loss: 7.088621
Epoch: 25, Loss: 6.335559
Epoch: 26, Loss: 5.693743
Epoch: 27, Loss: 5.142452
Epoch: 28, Loss: 4.665162
Epoch: 29, Loss: 4.248985
Epoch: 30, Loss: 3.883771
Epoch: 31, Loss: 3.561386
Epoch: 32, Loss: 3.275279
Epoch: 33, Loss: 3.020121
Epoch: 34, Loss: 2.791535
Epoch: 35, Loss: 2.585899
Epoch: 36, Loss: 2.400202
Epoch: 37, Loss: 2.231921
Epoch: 38, Loss: 

In [39]:
def predict(model, question, threshold=0.5):
  # convert question to neumbers
  neumerical_question = word_to_index(question, vocab)

  # tensor and send to model

  output = model(torch.tensor(neumerical_question)).unsqueeze(0)

  # convert logits to probability

  probs = torch.nn.functional.softmax(output,dim=1)

  # find the index of max prob

  value, index = torch.max(probs, dim=1)

  if value < threshold:
    print("i dont know")


  print(list(vocab.keys())[index])


In [40]:
print(predict(model, "What is the capital of Japan?"))

tokyo
None
